/**
 * @description       :
 * @author            : Rakshak Rajjoo
 * @last modified on  : 31/01/2022
 * @last modified by  : Rakshak Rajjoo
 * Modifications Log
 * Ver   Date         Author           Modification
 * 1.0   31/01/2022   Rakshak Rajjoo   Initial Version
 **/
public with sharing class AP02_HandlePassFail {
    public static void populatePassFail(List<ModuleEnrolled__c> lstMdEnrNew) {
    }
}